FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY cloud_app.py .

ENV PORT=8080
ENV PROJECT_ID=wprojectl
ENV LOCATION=us-central1

EXPOSE 8080

CMD ["python", "cloud_app.py"]
