apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: e76eb51b-88b5-4f3a-9e21-2071a4b75f1d
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/wprojectl/cloud-run-source-deploy/pc28-push-endpoints
    run.googleapis.com/build-name: projects/644485179199/locations/us-central1/builds/e76eb51b-88b5-4f3a-9e21-2071a4b75f1d
    run.googleapis.com/build-source-location: gs://run-sources-wprojectl-us-central1/services/pc28-push-endpoints/1758149266.888159-a34150fe49d448a8a08808c547b960fa.zip#1758149268046718
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://pc28-push-endpoints-644485179199.us-central1.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: pc28-push-endpoints
  namespace: '644485179199'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 538.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: vxlnlgxjud
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/wprojectl/cloud-run-source-deploy/pc28-push-endpoints@sha256:39341d936aecc4f248e4b713dafd76cf1b2ef818316c3a071db08b7dc80d716e
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 644485179199-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
